version: "3.8"

services:
  db:
    image: postgres:15
    container_name: my_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydb"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    depends_on:
      - seed
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@my_db:5432/mydb
    networks:
      - app-network

  seed:
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile.seed
    depends_on:
      db:
        condition: service_healthy
        restart: true
    image: "seed"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
