FROM --platform=linux/amd64 node:20-alpine AS deps
RUN apk add --no-cache libc6-compat openssl postgresql-client bash
WORKDIR /app

COPY scripts ./
COPY prisma ./

COPY package.json pnpm-lock.yaml\* ./
RUN npm install -g pnpm && pnpm i

RUN chmod +x seed.sh

CMD ["./seed.sh"]